### ISSUE TITLE
Annotation error

### ISSUE THREAD

**Issue by 789748456v** [wooorm/metaphone#12]
The file 'index.js' line 59
The annotation said  '  // WH becomes H, WR becomes R, W if followed by a vowel    '
According to the rules of this algorithm, i think 'WH' should become 'W' now
'WH' transforms to 'W' if at the beginning.

**Comment by wooorm** [comment]
Can you please back your statements up with sources.

**Comment by 789748456v** [comment]
In fact, the code is OK
I mean the error in annotation
And your code backs my statements up, when 'WH' is input, the output is 'W'
But your annotation said 'WH' becomes 'H'

**Comment by wooorm** [comment]
This algorithm is ancient, and shouldn’t be used.
Are you only reading the comments? Are you debugging the code?
Could definitely have problems in the comments.
`W` is also different depending on place.

**Comment by 789748456v** [comment]
Yes, I ran tests on the website you deployed and indeed this issue occurred. 
Of course, this issue is only a discrepancy between the comments and the code, and it can be fixed or not. 
By the way, I am using a new programming language to implement your code logic, so I discovered this issue. 
Thank you very much for your reply
